Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 80

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/BlockLength:
  Max: 200

Metrics/AbcSize:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
